# Generic API Service Configuration for Bootstrap Demo
# This configuration disables startup validation so the demo can control validation

application:
  name: cordal-api-service-demo

server:
  host: localhost
  port: 8080

database:
  url: jdbc:h2:./data/api-service-config;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
  username: sa
  password: ""
  driver: org.h2.Driver
  createIfMissing: true

swagger:
  enabled: true
  path: /swagger

# Configuration source and directory scanning
config:
  source: yaml
  loadFromYaml: false

  # Directories to scan for configuration files
  directories:
    - "generic-config"
    - "../generic-config"

  # Naming patterns for configuration files
  patterns:
    databases: ["*-database.yml", "*-databases.yml"]
    queries: ["*-query.yml", "*-queries.yml"]
    endpoints: ["*-endpoint.yml", "*-endpoints.yml", "*-api.yml"]

# Configuration validation settings - DISABLED for demo
validation:
  runOnStartup: false  # Disabled so demo can control validation
  validateOnly: false
  validateEndpoints: false
