server:
  host: localhost
  port: 8080

database:
  url: jdbc:h2:./data/stocktrades;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
  username: sa
  password: ""
  driver: org.h2.Driver

swagger:
  enabled: true
  path: /swagger

# Configuration file paths
config:
  paths:
    databases: "config/databases.yml"
    queries: "config/queries.yml"
    endpoints: "config/api-endpoints.yml"
