# Generic API Service Configuration

application:
  name: generic-api-service

server:
  host: localhost
  port: 8080

database:
  url: jdbc:h2:./data/api-service-config;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
  username: sa
  password: ""
  driver: org.h2.Driver
  createIfMissing: true  # Create database if it doesn't exist

swagger:
  enabled: true
  path: /swagger

# Configuration source and file paths
config:
  source: yaml  # Options: yaml, database
  # Load configuration data from YAML files into database (only when source is database)
  loadFromYaml: false  # Set to true to populate database from YAML files on startup
  paths:
    # Configuration files are located in the generic-config folder at project root
    # Using ./ prefix to indicate external files relative to working directory
    databases: "./generic-config/databases.yml"
    queries: "./generic-config/queries.yml"
    endpoints: "./generic-config/api-endpoints.yml"
