
server:
  host: localhost
  port: 8080

database:
  url: jdbc:h2:./data/api-service-config;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
  username: sa
  password: ""
  driver: org.h2.Driver
  createIfMissing: true  # Create database if it doesn't exist

swagger:
  enabled: true
  path: /swagger

# Configuration source and file paths
config:
  source: yaml  # Options: yaml, database
  paths:
    databases: "../generic-config/databases.yml"
    queries: "../generic-config/queries.yml"
    endpoints: "../generic-config/api-endpoints.yml"
