# Generic API Service Configuration

application:
  name: generic-api-service

server:
  host: localhost
  port: 8080

database:
  url: jdbc:h2:./data/api-service-config;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
  username: sa
  password: ""
  driver: org.h2.Driver
  createIfMissing: true  # Create database if it doesn't exist

swagger:
  enabled: true
  path: /swagger

# Configuration source and file paths
config:
  source: yaml  # Options: yaml, database
  # Load configuration data from YAML files into database (only when source is database)
  loadFromYaml: false  # Set to true to populate database from YAML files on startup
  paths:
    # Configuration files are located in the generic-config folder at project root
    # Using ../ prefix to go up one level from generic-api-service to project root
    databases: "./generic-config/stocktrades-databases.yml"
    queries: "./generic-config/stocktrades-queries.yml"
    endpoints: "./generic-config/stocktrades-api-endpoints.yml"

# Configuration validation settings
validation:
  # Run validation during normal application startup
  runOnStartup: false  # Set to true to validate configurations on every startup
  # Run only validation and exit (for standalone configuration checking)
  validateOnly: false  # Set to true to run validation checks and exit without starting server
