endpoints:
  stock-trades-list:
    path: "/api/generic/stock-trades"
    method: "GET"
    query: "stock-trades-all"
    countQuery: "stock-trades-count"
    description: "Get all stock trades with pagination"
    pagination:
      enabled: true
      defaultSize: 20
      maxSize: 100
    parameters:
      - name: "page"
        type: "INTEGER"
        source: "QUERY"
        required: false
        defaultValue: "1"
      - name: "size"
        type: "INTEGER"
        source: "QUERY"
        required: false
        defaultValue: "20"
      - name: "async"
        type: "BOOLEAN"
        source: "QUERY"
        required: false
        defaultValue: "false"
    response:
      type: "PAGED"
      fields:
        - name: "id"
          type: "LONG"
        - name: "symbol"
          type: "STRING"
        - name: "quantity"
          type: "INTEGER"
        - name: "price"
          type: "DECIMAL"
        - name: "trade_date_time"
          type: "TIMESTAMP"
        - name: "trader_id"
          type: "STRING"
          
  stock-trades-by-symbol:
    path: "/api/generic/stock-trades/symbol/{symbol}"
    method: "GET"
    query: "stock-trades-by-symbol"
    countQuery: "stock-trades-by-symbol-count"
    description: "Get stock trades by symbol with pagination"
    pagination:
      enabled: true
      defaultSize: 20
      maxSize: 100
    parameters:
      - name: "symbol"
        type: "STRING"
        source: "PATH"
        required: true
      - name: "page"
        type: "INTEGER"
        source: "QUERY"
        required: false
        defaultValue: "1"
      - name: "size"
        type: "INTEGER"
        source: "QUERY"
        required: false
        defaultValue: "20"
      - name: "async"
        type: "BOOLEAN"
        source: "QUERY"
        required: false
        defaultValue: "false"
    response:
      type: "PAGED"
      fields:
        - name: "id"
          type: "LONG"
        - name: "symbol"
          type: "STRING"
        - name: "quantity"
          type: "INTEGER"
        - name: "price"
          type: "DECIMAL"
        - name: "trade_date_time"
          type: "TIMESTAMP"
        - name: "trader_id"
          type: "STRING"
          
  stock-trades-by-trader:
    path: "/api/generic/stock-trades/trader/{trader_id}"
    method: "GET"
    query: "stock-trades-by-trader"
    countQuery: "stock-trades-by-trader-count"
    description: "Get stock trades by trader ID with pagination"
    pagination:
      enabled: true
      defaultSize: 20
      maxSize: 100
    parameters:
      - name: "trader_id"
        type: "STRING"
        source: "PATH"
        required: true
      - name: "page"
        type: "INTEGER"
        source: "QUERY"
        required: false
        defaultValue: "1"
      - name: "size"
        type: "INTEGER"
        source: "QUERY"
        required: false
        defaultValue: "20"
      - name: "async"
        type: "BOOLEAN"
        source: "QUERY"
        required: false
        defaultValue: "false"
    response:
      type: "PAGED"
      fields:
        - name: "id"
          type: "LONG"
        - name: "symbol"
          type: "STRING"
        - name: "quantity"
          type: "INTEGER"
        - name: "price"
          type: "DECIMAL"
        - name: "trade_date_time"
          type: "TIMESTAMP"
        - name: "trader_id"
          type: "STRING"
          
  stock-trades-by-date-range:
    path: "/api/generic/stock-trades/date-range"
    method: "GET"
    query: "stock-trades-by-date-range"
    countQuery: "stock-trades-by-date-range-count"
    description: "Get stock trades within date range with pagination"
    pagination:
      enabled: true
      defaultSize: 20
      maxSize: 100
    parameters:
      - name: "start_date"
        type: "STRING"
        source: "QUERY"
        required: true
      - name: "end_date"
        type: "STRING"
        source: "QUERY"
        required: true
      - name: "page"
        type: "INTEGER"
        source: "QUERY"
        required: false
        defaultValue: "1"
      - name: "size"
        type: "INTEGER"
        source: "QUERY"
        required: false
        defaultValue: "20"
      - name: "async"
        type: "BOOLEAN"
        source: "QUERY"
        required: false
        defaultValue: "false"
    response:
      type: "PAGED"
      fields:
        - name: "id"
          type: "LONG"
        - name: "symbol"
          type: "STRING"
        - name: "quantity"
          type: "INTEGER"
        - name: "price"
          type: "DECIMAL"
        - name: "trade_date_time"
          type: "TIMESTAMP"
        - name: "trader_id"
          type: "STRING"
          
  stock-trade-by-id:
    path: "/api/generic/stock-trades/{id}"
    method: "GET"
    query: "stock-trade-by-id"
    description: "Get stock trade by ID"
    parameters:
      - name: "id"
        type: "LONG"
        source: "PATH"
        required: true
      - name: "async"
        type: "BOOLEAN"
        source: "QUERY"
        required: false
        defaultValue: "false"
    response:
      type: "SINGLE"
      fields:
        - name: "id"
          type: "LONG"
        - name: "symbol"
          type: "STRING"
        - name: "quantity"
          type: "INTEGER"
        - name: "price"
          type: "DECIMAL"
        - name: "trade_date_time"
          type: "TIMESTAMP"
        - name: "trader_id"
          type: "STRING"
          
  performance-metrics-list:
    path: "/api/generic/metrics"
    method: "GET"
    query: "performance-metrics-all"
    countQuery: "performance-metrics-count"
    description: "Get all performance metrics with pagination"
    pagination:
      enabled: true
      defaultSize: 50
      maxSize: 200
    parameters:
      - name: "page"
        type: "INTEGER"
        source: "QUERY"
        required: false
        defaultValue: "1"
      - name: "size"
        type: "INTEGER"
        source: "QUERY"
        required: false
        defaultValue: "50"
      - name: "async"
        type: "BOOLEAN"
        source: "QUERY"
        required: false
        defaultValue: "false"
    response:
      type: "PAGED"
      fields:
        - name: "id"
          type: "LONG"
        - name: "endpoint_name"
          type: "STRING"
        - name: "execution_time_ms"
          type: "LONG"
        - name: "success"
          type: "BOOLEAN"
        - name: "timestamp"
          type: "TIMESTAMP"
